### ISSUE TITLE
Custom Schema

### ISSUE THREAD

**Issue by whargrove** [justinwrobel/bbmd#1]
@justinwrobel – I was wondering if you had any plans for "missing documentation" regarding setting up a custom schema in Blackboard Learn?

**Comment by justinwrobel** [comment]
I don't currently have any plans but thats a good idea. If you need help now: All you have to do is create an xml file in /WEB-INF/schema/${project.name}/schema.xml and use the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="http://www.blackboard.com/bb-manifest-plugin"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.blackboard.com/bb-manifest-plugin http://fibbba.blackboard.com/xsd/bb-manifest-plugin.xsd">
```

I'll work on a tutorial in the mean time.

**Comment by whargrove** [comment]
@justinwrobel I was going to work on one but didn't want to duplicate effort if you already had one in progress.

**Comment by justinwrobel** [comment]
I put up a very [basic tutorial](https://github.com/justinwrobel/bbmd/blob/master/CustomDbSchema.md). If you've got any suggestions let me know or just update/create a new one. The more the merrier IMHO.

**Comment by shaneargo** [comment]
Extremely late to the party, but I'm going to put this here in case someone else stumbles upon this. Here is a blog I wrote about Blackboard schema.xml a while back: https://blog.alltheducks.com/post/introduction_to_blackboard_schema_xml/

**Comment by justinwrobel** [comment]
I'll say! But very welcome! Nice article!
